### ISSUE TITLE
Main navigation "Development" link broken due to removed JIRA

### ISSUE THREAD

**Issue by kdambekalns** [doctrine/doctrine-website-sphinx#102]
…'nuff said! :)

**Comment by mikeSimonson** [comment]
@kdambekalns well no not enough. Where is that development link ?

**Comment by kdambekalns** [comment]
<img width="802" alt="home_ _doctrine_project" src="https://cloud.githubusercontent.com/assets/95873/11748004/6a36b2d6-a026-11e5-86f6-66e4a8e18e87.png">

**Comment by mikeSimonson** [comment]
@kdambekalns thanks, It was too obvious for me.

**Comment by mikeSimonson** [comment]
Fixed. Thanks
