### ISSUE TITLE
ORM 2.3.4 link broken

### ISSUE THREAD

**Issue by Shakespeare2000** [doctrine/doctrine-website-sphinx#19]
The 'Download Archive' link is broken on http://www.doctrine-project.org/projects/orm.html.

http://www.doctrine-project.org/downloads/ doesn't shows the archive as well.

**Comment by mikeSimonson** [comment]
I believe that the archive are not put on our website anymore. Go to the github release page if you really need them. Thanks @Shakespeare2000
