### ISSUE TITLE
CouchDB Link = 404ing

### ISSUE THREAD

**Issue by franz-josef-kaiser** [doctrine/doctrine-website-sphinx#20]
Links from the CouchDB [GitHub repo](https://github.com/doctrine/couchdb-odm) to 

    http://www.doctrine-project.org/docs/couchdb_odm/1.0/en/

are 404s. The actual link on this page to

    http://docs.doctrine-project.org/projects/doctrine-couchdb-odm/en/latest/

404s as well.

**Comment by mikeSimonson** [comment]
seems fixed. thanks @franz-josef-kaiser
