### ISSUE TITLE
Link to latest 2.4 documentation not working

### ISSUE THREAD

**Issue by flack** [doctrine/doctrine-website-sphinx#23]
Not sure if this is the right bug tracker, but I thought I'd try my luck. On the page:

http://www.doctrine-project.org/projects/orm.html

The second link from the top ("Latest Documentation") points to

http://www.doctrine-project.org/docs/orm/2.4/en/index.html

which is a 404. The correct link AFAICT should be 

http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/

I've tried locating this in the source to make a PR, but frankly, I have no idea how this sphinx thing works, so someone else will have to take care of this :-)

**Comment by mikeSimonson** [comment]
Seems fixed. Thanks @flack
