### ISSUE TITLE
Links to DBAL and ORM Documentation broken on home page

### ISSUE THREAD

**Issue by jdines** [doctrine/doctrine-website-sphinx#26]
From doctrine-project.org the link to the Database Abstraction Layer documentation is: http://www.doctrine-project.org/docs/dbal/2.4/en/index.html but that is broken.  It should probably be: http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/ which works.  The link to http://www.doctrine-project.org/docs/orm/2.4/en/index.html is also broken as well, and should probably be http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/

**Comment by mikeSimonson** [comment]
Can't find the faulty link anymore.
