### ISSUE TITLE
Broken Download Link

### ISSUE THREAD

**Issue by feamsr00** [doctrine/doctrine-website-sphinx#30]
Hi There,

FYI: on the page http://www.doctrine-project.org/projects/orm.html the download link for the current archive is broken.

eg: http://www.doctrine-project.org/downloads/DoctrineORM-2.3.4-full.tar.gz
That effectively returns a 404.

**Comment by mikeSimonson** [comment]
This version is not supported anymore and I think that no download from our website is provided anymore. You can still fetch it on github though.

**Comment by feamsr00** [comment]
Thanks for taking a look at this. 

Humm. Perhaps there should be a simple link to the github-zipball...thing. This way users that may not have composer available will clearly know what to get.

(note: it might also be a good idea to list a support policy on the site, *or* at least grey out or label the deprecated versions)

**Comment by mikeSimonson** [comment]
@feamsr00 Not sure about the download link but I created a new issue so that the unsupported stuff as clearly marked as unsupported. #108

**Comment by feamsr00** [comment]
@mikeSimonson you can use the link (assuming the repo has everything an end-user needs) from the "Download zip" button on the respective branch like so:

https://github.com/doctrine/doctrine2/archive/v2.5.2.zip
(it used to have 'zipball' in the url)

Hope that helps. Thanks for #108!
