### ISSUE TITLE
PHPCR-ODM Documentation Link Broken

### ISSUE THREAD

**Issue by dantleech** [doctrine/doctrine-website-sphinx#31]
Hi,

It is no longer possible to access the PHPCR-ODM documentation from the link on the website, e.g. from:

http://www.doctrine-project.org/projects/phpcr-odm.html

Which links to a 404 at:

http://www.doctrine-project.org/docs/phpcr-odm/latest/en/index.html

**Comment by mikeSimonson** [comment]
@beberlei @dantleech This seems fixed.

**Comment by dbu** [comment]
the "API (1.2)" links to a 404, only "Latest Documentation" works. also, we tagged 1.3.0 yesterday, but the page still says 1.2 is the latest. do we need to wait for the next deployment?
