### ISSUE TITLE
Download Archive for DoctrineORM-2.3.4-full.tar.gz not working - link broken.

### ISSUE THREAD

**Issue by amitkriplani** [doctrine/doctrine-website-sphinx#32]
http://www.doctrine-project.org/downloads/DoctrineORM-2.3.4-full.tar.gz is broken

**Comment by mikeSimonson** [comment]
@beberlei Seems like the new version are not pushed on the server. Closing the issue ?

**Comment by Ocramius** [comment]
We're not maintaining 2.3.x anyway.

Closing.
